# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='date_exam',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0427\u0430\u0441 \u0435\u043a\u0437\u0430\u043c\u0435\u043d\u0443'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='group_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='\u0413\u0440\u0443\u043f\u0430'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u041f\u0440\u0435\u0434\u043c\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u0412\u0438\u043a\u043b\u0430\u0434\u0430\u0447'),
        ),
        migrations.CreateModel(
            name='MonthJournal',
            fields=[
                ('present_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.Present')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', unique_for_month='date', verbose_name='\u0421\u0442\u0443\u0434\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u041c\u0456\u0441\u044f\u0447\u043d\u0438\u0439 \u0436\u0443\u0440\u043d\u0430\u043b',
                'verbose_name_plural': '\u041c\u0456\u0441\u044f\u0447\u043d\u0456 \u0436\u0443\u0440\u043d\u0430\u043b\u0438',
            },
            bases=('students.present',),
        ),
    ]
