# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20171108_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_ptr',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='student',
        ),
        migrations.DeleteModel(
            name='MonthJournal',
        ),
        migrations.DeleteModel(
            name='Present',
        ),
    ]
